### ISSUE TITLE
Package missing in current win-64 channels:   - tweet-preprocessor

### ISSUE THREAD

**Issue by MUATHALALI** [s/preprocessor#12]

**Comment by iamRusty** [comment]
Go to `C:/Anaconda/Scripts` and then run 

`pip install tweet-preprocessor`

**Comment by MUATHALALI** [comment]
it doesn't work:
C:\Users\Muath\Anaconda3\Scripts>pip install tweet-preprocessor
Collecting tweet-preprocessor
  Using cached tweet-preprocessor-0.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Muath\AppData\Local\Temp\pip-build-e46h9vkx\tweet-preprocessor\setup.py", line 6, in <module>
        long_description = f.read()
      File "C:\Users\Muath\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 652: character maps to <undefined>
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Muath\AppData\Local\Temp\pip-build-e46h9vkx\tweet-preprocessor\

**Comment by iamRusty** [comment]
This bug only happens in Windows environment. I've already made a fix #11 for it but the author still hasn't approved it. For the meantime, download my [repository](https://github.com/iamRusty/preprocessor) and do [manual installation](https://github.com/iamRusty/preprocessor/blob/master/README.rst).

**Comment by iamRusty** [comment]
If still doesn't work, even if the install is successful, you should add the package to your anaconda environment. :)

**Comment by MUATHALALI** [comment]
How can I add the package to ACONDA? Do you means just copy the file to Cona file @iamRusty

**Comment by MUATHALALI** [comment]
"preprocessor' has no attribute 'clean' @iamRusty

**Comment by iamRusty** [comment]
I'm sorry that it's still not working for you. Can you post the "tweet" that gives this error?

**Comment by fultonm** [comment]
It's the "Package" that's giving this error

**Comment by EvandNoth** [comment]
Firstly you must install preprocessor library and after that install tweet-preprocessor module

**Comment by s** [comment]
Hey there, `UnicodeDecodeError` @MUATHALALI mentioned is fixed in `v0.6.0` branch. And the issue @fultonm mentioned, you need to import the library as follows:
```
import preprocessor as p
```
and then you can call it using `p`
```
p.clean(str)
```

However if you still get an error, please create a new issue using below template. Cheers.

name: Bug report
about: Create a report to help us improve
title: ''
labels: bug
assignees: ''

Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

OS: [e.g. macOS]
Python Version: [e.g. 3.7.3]
preprocessor version [e.g. 0.6.0]
Additional context
Add any other context about the problem here.
